store error messages as array

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -165,18 +165,19 @@ jobs:
       continue-on-error: true
       run: |
         LOGFILE=output.log
-        EXTRA_MSG=""
+        ERR_MSGS=()
         ERR_COUNT=0
         pytest -vv tests/*_test.py tests/test_*.py -m "strict_endpoints_test" > $LOGFILE 2>&1 || \
           while read FAIL; do
             ANALYSIS=`echo ${FAIL##*strict\[} | cut -d "]" -f1` # get analysis name from pattern "strict[<ANALYSIS>]"
-            ERR_COUNT=$((ERR_COUNT+1))
+            ERR_COUNT=$(( ${#ERR_MSGS[@]} + 1 ))
             REASON=`grep "^E       " $LOGFILE | head -n $ERR_COUNT | tail -n 1` # get fail reason
             REASON=${REASON:8} # remove prefix
-            EXTRA_MSG="$EXTRA_MSG::warning ::Analyses endpoint '$ANALYSIS' was not available: $REASON\n"
+            ERR_MSGS+=("::warning ::Analyses endpoint '$ANALYSIS' was not available: $REASON") # use GitHub's warning syntax
           done <<< `grep "FAILED.*\[" $LOGFILE | grep -v "%"` # get summary lines with failing tests, ignore progress lines
         cat $LOGFILE
-        echo -n $EXTRA_MSG # flag warning to GitHub, remove trailing new lines
+        for ERR_MSG in "${ERR_MSGS[@]}"; do; echo $ERR_MSG; done # flag errors
+        if [ $ERR_COUNT>0 ]; then; exit 1; fi # fail if there were any errors
     - name: Setup Sauce Connect
       uses: saucelabs/sauce-connect-action@v3.0.0
       if: startsWith(matrix.python-version, '3.9')
